### ISSUE TITLE
post flow

### ISSUE THREAD

**Issue by noumenon272** [alex6o/node-red-contrib-dynamic-dimmer#14]
I'm confused as to how to replicate your advanced inject node that you demo in the gif. will you post that flow so that it can be imported?

thanks

**Comment by alex6o** [comment]
Hi! you can checkout the following sample flow https://github.com/alex6o/node-red-contrib-dynamic-dimmer/blob/master/samples/basics/dynamic_dimmer_basics.json which is quite similar!

**Comment by noumenon272** [comment]
thanks, I understand better now.

this node does a lot of what I want it to, but there are a couple of additional features that would make it more useful. I'd like to be able to specify both the start and end points of the dim. Currently it stores the last final value as its starting point. I want to be able to specify for example: "dim from 20 to 0". If I do that twice now, only the first time will do anything.

also, it would be nice if those commands/values were stored in properties (like msg.payload.value, msg.payload.set, etc). this would make it easier to modify those values with other nodes. 

ultimately I want to be able to store the current state of a dimmer in a value and then dim up and down from that value. If the value changes outside of node red (by pressing a physical dimmer switch for instance), then I want to be able to start the dim from that point.

maybe thats outside the purview of what you're trying to do, or maybe I'm missing something. dimming seems to be the main place that node red falls flat as a home automation tool.

thanks

**Comment by alex6o** [comment]
One of the main concepts of this node is that it is actually stateful. It is intended to behave similar to a physical dimmer which is directly connected to e.g. a bulb.  If you want to change the min and max at "runtime" you can simply send it along with the payload:
{code}
{
    "msg": {
        "payload":{
            "target": 0.5,
            "command": "DIM",
            "config": {
                "eventInterval": 600,
                "steps": 10,
                "minValue": 0,
                "maxValue": 75
            }
        }
    }
}
{code}
Due to the stateful characteristic of the node it is at the moment not possible to "dim from 20 to 0" twice. In that case you need to send the the `SET` command before starting another dim operation.

@store the current state: exposing the internal state should not be necessary, because with the physical dimmer you just need to provide the target value (between 0 and 1) and the node will take care of the rest :)
